name: Deploy Next.js to Azure Web App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Next.js
        run: npm run build

      - name: Zip project
        run: zip -r next-app.zip . -x ".git/*"

      - name: Login to Azure using SERVICE PRINCIPAL
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B0CDB0690DE4F39A32956E08716A15E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D93B3F2AF8C4369A71ADF410EA2D568 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A87E1C22517543279B2A0085A2ACE2BD }}
          client-secret: ${{ secrets.AZUREAPPSERVICE_CLIENTSECRET }}



      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "zuperiorcrm"
          package: "next-app.zip"
